In [1]:
from google.colab import files
uploaded = files.upload()

Saving fifaValue.csv to fifaValue.csv

In [77]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

players = pd.read_csv("fifaValue.csv", delimiter=',', header=0)
players.head()

,Age,Nationality,Club,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,Position,Contract Valid Until,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Value
0,31,Argentina,FC Barcelona,Left,5.0,4.0,4.0,Medium/ Medium,RF,2021,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,�110.5M
1,33,Portugal,Juventus,Right,5.0,4.0,5.0,High/ Low,ST,2022,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,�77M
2,26,Brazil,Paris Saint-Germain,Right,5.0,5.0,5.0,High/ Medium,LW,2022,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,�118.5M
3,27,Spain,Manchester United,Right,4.0,3.0,1.0,Medium/ Medium,GK,2020,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,�72M
4,27,Belgium,Manchester City,Right,4.0,5.0,4.0,High/ High,RCM,2023,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,�102M

In [78]:
players.describe(include='all')

,Age,Nationality,Club,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,Position,Contract Valid Until,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Value
count,18207.000000,18207,17966,18159,18159.000000,18159.000000,18159.000000,18159,18147,17918,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18207
unique,NaN,164,651,2,NaN,NaN,NaN,9,27,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,217
top,NaN,England,FC Barcelona,Right,NaN,NaN,NaN,Medium/ Medium,ST,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,�1.1M
freq,NaN,1662,33,13948,NaN,NaN,NaN,9810,2152,4819,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,431
mean,25.122206,NaN,NaN,NaN,1.113222,2.947299,2.361308,NaN,NaN,NaN,...,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887,NaN
std,4.669943,NaN,NaN,NaN,0.394031,0.660456,0.756164,NaN,NaN,NaN,...,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119,NaN
min,16.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN,...,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN
25%,21.000000,NaN,NaN,NaN,1.000000,3.000000,2.000000,NaN,NaN,NaN,...,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000,NaN
50%,25.000000,NaN,NaN,NaN,1.000000,3.000000,2.000000,NaN,NaN,NaN,...,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000,NaN
75%,28.000000,NaN,NaN,NaN,1.000000,3.000000,3.000000,NaN,NaN,NaN,...,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000,NaN
max,45.000000,NaN,NaN,NaN,5.000000,5.000000,5.000000,NaN,NaN,NaN,...,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000,NaN

In [136]:
#Removing Special Character from Variable “Value”

import decimal
df_new = players['Value'].str.replace('[�]','')

# Converting K to Mill if Required
new_Value = []
for i in df_new:
  if 'K' in i:
    data = str(round(decimal.Decimal(int(i.replace('K',''))/1000000),6)) + 'M'
    new_Value.append(data)
  else:
    new_Value.append(i)

players["NRM_Value"] = new_Value

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  after removing the cwd from sys.path.

In [171]:
# Convert Year and replaced Null with NA
from os import error
from datetime import datetime
import numpy as np

new_CVU = []

for each in players["Contract Valid Until"]:
  try:
    if len(each) > 4 :
      data = '20' + each[7:9]
      new_CVU.append(data)
    else:
      data = each
      new_CVU.append(each)
  except Exception :
    data = 'NA'
    new_CVU.append(data)
  
players["NRM_CVU"] = new_CVU

players.to_csv("NRM_Data.csv")

In [172]:
from google.colab import files
files.download("NRM_Data.csv")